server:
  port: 3000
spring:
  application:
    name: test2
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/douyin?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 263269
  redis:
    host: 192.168.59.128
    port: 6379
    password: 263269
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  jpa:
    open-in-view: false
logging:
  level:
    com.hmdp: debug
