server:
  port: 3000
spring:
  application:
    name: test2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/douyin?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 263269
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  jpa:
    open-in-view: false
  data:
    redis:
      host: 192.168.59.128
      port: 6379
      password: 263269
      lettuce:
        pool:
          max-active: 30
          max-idle: 30
          min-idle: 1
          time-between-eviction-runs: 10s
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b
logging:
  level:
    com.hmdp: debug
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
